server:
  port: 8089
spring:
  application:
    name: portal-recruit
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recruit?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    #    url: jdbc:mysql://gz-cdb-m8ym7w9t.sql.tencentcdb.com:59111/recruit?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    #    username: xiaohaihai
    #    password: xiaohaihai123
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  servlet:
    multipart:
      max-file-size: 10MB #单个上传文件的最大大小
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@register:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    #把容器内的地址换成服务器的地址注册到eureka中心，外网是无法访问容器内的地址
    prefer-ip-address: true

swagger:
  print-init: true
  enabled: true
  dockets:
    docket-api:
      base-package: com.portal.controller
      group-name: 小海
      api-info:
        title: 招聘模块接口
        description: RESTful接口描述
        version: 1.0
        license: Apache 2.0
        contact:
          name: 小海
          url: https://blog.csdn.net/weixin_39030846/
          email: 2631565336@qq.com
